version: "3.9"
services:
  web-api:
    build: 
      dockerfile: WebApi/Dockerfile
      context: backend
    container_name: AspDotNetApi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Mongo__ConnectionString=mongodb://db:27017
    ports:
      - "5170:80"
